#%RAML 1.0 NamedExample
newsResponse:
  - id: 186703774208
    stamp: 2019-08-01T17:58:03.000Z
    headline: Sound Editor Update!
    url: https://scratch.mit.edu/discuss/topic/365737/
    image: https://66.media.tumblr.com/2bbe2bc9317585c1de96c91f56bb061b/tumblr_inline_pad1ik8d2k1tqsk9m_540.png
    copy: We have an update for you. See here for more information…